
title: Neural networks based ensemble classifier for phishing link detection
description: Wojciech Gałka, Jan G. Bazan, Urszula Bentkowska, Marcin Mrukowicz
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
